"""Reproducible cleaning script — generated by Distill Agent.

Session : 20260530-062547-f0fd71
Source  : adult_sample.csv
Result  : 6,000x15 raw  ->  5,878x21 clean

This script replays the whole cleaning session deterministically.
It uses only pandas / numpy — no LLM, no agent.

============================================================
WHAT THIS SCRIPT EXPECTS AS INPUT
============================================================

The raw structured data file is:  adult_sample.csv
  (6,000 rows x 15 columns)

────────────────────────────────────────────────────────────
HOW TO CALL clean()
────────────────────────────────────────────────────────────

    python clean_script.py  adult_sample.csv
    # or in Python:
    from clean_script import clean
    df = clean("adult_sample.csv")
    # You may also pass a pandas DataFrame directly:
    df = clean(your_raw_dataframe)

OUTPUT
──────
Running this script produces the format(s) selected during cleaning:
clean.csv    — the cleaned, model-ready structured dataset

────────────────────────────────────────────────────────────
SETUP / ENVIRONMENT
────────────────────────────────────────────────────────────

Requires Python >=3.10  (tested on 3.10–3.12).
This script is standalone — it needs only these packages:
    pandas>=2.1     # dataframe engine (always required)
    numpy>=1.26    # numeric arrays (always required)

Install everything (a requirements.txt and environment.yml are written
alongside this script):
    pip install -r requirements.txt
    # or with conda:
    conda env create -f environment.yml && conda activate distill-clean

============================================================
"""

from __future__ import annotations

import sys
import tempfile
import zipfile
from pathlib import Path

import numpy as np
import pandas as pd

_SOURCE_FILENAME = 'adult_sample.csv'


def _load_source(
    source: 'str | Path | pd.DataFrame',
    companion_dir: 'str | Path | None' = None,
) -> 'tuple[pd.DataFrame, Path | None]':
    """Read raw data from a file path, ZIP archive, or DataFrame."""
    if isinstance(source, pd.DataFrame):
        return source.copy(), Path(companion_dir) if companion_dir else None
    _p = Path(source)
    if _p.suffix.lower() == '.zip':
        _tmp = Path(tempfile.mkdtemp())
        with zipfile.ZipFile(_p) as _zf:
            _zf.extractall(_tmp)
        _candidates = list(_tmp.rglob(_SOURCE_FILENAME))
        if not _candidates:
            _candidates = sorted(_tmp.rglob('*.csv'))
        if not _candidates:
            raise FileNotFoundError(f'No CSV found inside {_p}.')
        # Prefer the CSV whose siblings include a target/label file (train split).
        def _priority(p: Path) -> int:
            siblings = {s.name.lower() for s in p.parent.iterdir()}
            return 0 if any(k in s for s in siblings
                           for k in ('train', 'dose', 'target', 'label')) else 1
        _main = sorted(_candidates, key=_priority)[0]
        if companion_dir is None:
            companion_dir = _main.parent
        return pd.read_csv(_main, dtype=object, keep_default_na=True), Path(companion_dir)
    _ext = _p.suffix.lower()
    if _ext in ('.xlsx', '.xls'):
        _df = pd.read_excel(_p, dtype=object)
    elif _ext == '.parquet':
        _df = pd.read_parquet(_p)
    elif _ext == '.json':
        _df = pd.read_json(_p, dtype=object)
    elif _ext in ('.sav',):
        _df = pd.read_spss(_p)
    elif _ext in ('.dta',):
        _df = pd.read_stata(_p)
    else:
        _df = pd.read_csv(_p, dtype=object, keep_default_na=True)
    return _df, Path(companion_dir) if companion_dir else None


def clean(
    source: 'str | Path | pd.DataFrame',
    companion_dir: 'str | Path | None' = None,
) -> pd.DataFrame:
    """Full pipeline: load → clean → join companions.

    source may be:
      - a ZIP file containing the raw CSV and companion files
      - the raw CSV / Excel / Parquet path
      - a raw pandas DataFrame (companion_dir must be supplied separately)

    """
    df, companion_dir = _load_source(source, companion_dir)

    # ============================================================
    # Stage: profile
    # ============================================================
    # profile: Profiled 15 variables across 6000 rows. 0 have missing values; 6 type-mismatch flags. (no data change)

    # ============================================================
    # Stage: companion
    # ============================================================
    # companion matching: 0 subject(s) missing companion — kept (paths reconstructed on demand)

    # ============================================================
    # Stage: format
    # ============================================================
    # rename 6 column(s) to snake_case
    df = df.rename(columns={"education-num": "education_num", "marital-status": "marital_status", "capital-gain": "capital_gain", "capital-loss": "capital_loss", "hours-per-week": "hours_per_week", "native-country": "native_country"})
    if 'workclass' in df.columns:
        # workclass: strip leading/trailing whitespace
        df['workclass'] = df['workclass'].where(df['workclass'].isna(), df['workclass'].astype(str).str.strip())
    if 'education' in df.columns:
        # education: strip leading/trailing whitespace
        df['education'] = df['education'].where(df['education'].isna(), df['education'].astype(str).str.strip())
    if 'marital_status' in df.columns:
        # marital_status: strip leading/trailing whitespace
        df['marital_status'] = df['marital_status'].where(df['marital_status'].isna(), df['marital_status'].astype(str).str.strip())
    if 'occupation' in df.columns:
        # occupation: strip leading/trailing whitespace
        df['occupation'] = df['occupation'].where(df['occupation'].isna(), df['occupation'].astype(str).str.strip())
    if 'relationship' in df.columns:
        # relationship: strip leading/trailing whitespace
        df['relationship'] = df['relationship'].where(df['relationship'].isna(), df['relationship'].astype(str).str.strip())
    if 'race' in df.columns:
        # race: strip leading/trailing whitespace
        df['race'] = df['race'].where(df['race'].isna(), df['race'].astype(str).str.strip())
    if 'sex' in df.columns:
        # sex: strip leading/trailing whitespace
        df['sex'] = df['sex'].where(df['sex'].isna(), df['sex'].astype(str).str.strip())
    if 'native_country' in df.columns:
        # native_country: strip leading/trailing whitespace
        df['native_country'] = df['native_country'].where(df['native_country'].isna(), df['native_country'].astype(str).str.strip())
    if 'income' in df.columns:
        # income: strip leading/trailing whitespace
        df['income'] = df['income'].where(df['income'].isna(), df['income'].astype(str).str.strip())
    if 'workclass' in df.columns:
        # workclass: convert missing-value sentinel(s) ['?'] to NaN
        df['workclass'] = df['workclass'].replace(["?"], np.nan)
    if 'occupation' in df.columns:
        # occupation: convert missing-value sentinel(s) ['?'] to NaN
        df['occupation'] = df['occupation'].replace(["?"], np.nan)
    if 'native_country' in df.columns:
        # native_country: convert missing-value sentinel(s) ['?'] to NaN
        df['native_country'] = df['native_country'].replace(["?"], np.nan)
    if 'age' in df.columns:
        # age: coerce to numeric
        df['age'] = pd.to_numeric(df['age'], errors='coerce')
    if 'fnlwgt' in df.columns:
        # fnlwgt: coerce to numeric
        df['fnlwgt'] = pd.to_numeric(df['fnlwgt'], errors='coerce')
    if 'education_num' in df.columns:
        # education_num: coerce to numeric
        df['education_num'] = pd.to_numeric(df['education_num'], errors='coerce')
    if 'capital_gain' in df.columns:
        # capital_gain: coerce to numeric
        df['capital_gain'] = pd.to_numeric(df['capital_gain'], errors='coerce')
    if 'capital_loss' in df.columns:
        # capital_loss: coerce to numeric
        df['capital_loss'] = pd.to_numeric(df['capital_loss'], errors='coerce')
    if 'hours_per_week' in df.columns:
        # hours_per_week: coerce to numeric
        df['hours_per_week'] = pd.to_numeric(df['hours_per_week'], errors='coerce')

    # ============================================================
    # Stage: duplicate
    # ============================================================
    # remove exact-duplicate rows, keep first of each group
    df = df.drop_duplicates(subset=["age", "workclass", "fnlwgt", "education", "education_num", "marital_status", "occupation", "relationship", "race", "sex", "capital_gain", "capital_loss", "hours_per_week", "native_country", "income"], keep='first')
    # near-duplicate cluster: skip (no row change)

    # ============================================================
    # Stage: missingness
    # ============================================================
    if 'workclass' in df.columns:
        # workclass: mode_impute (imputed value recorded by the session)
        df['workclass'] = df['workclass'].fillna('Private')
    if 'occupation' in df.columns:
        # occupation: mode_impute (imputed value recorded by the session)
        df['occupation'] = df['occupation'].fillna('Craft-repair')
    if 'native_country' in df.columns:
        # native_country: drop rows with missing value
        df = df.dropna(subset=['native_country'])

    # ============================================================
    # Stage: outlier
    # ============================================================
    # age: outliers reviewed, no change (leave_as_is)
    # fnlwgt: outliers reviewed, no change (inspect)
    # education_num: outliers reviewed, no change (leave_as_is)
    # capital_gain: outliers reviewed, no change (inspect)
    # capital_loss: outliers reviewed, no change (inspect)
    # hours_per_week: outliers reviewed, no change (leave_as_is)

    # ============================================================
    # Stage: binning
    # ============================================================
    if 'capital_gain' in df.columns:
        # capital_gain: bin_quantile bin into 1 groups → 'capital_gain_bin'
        df['capital_gain_bin'] = pd.cut(
            pd.to_numeric(df['capital_gain'], errors='coerce'), bins=[-1e-09, 99999.000000001],
            labels=['all'], include_lowest=True
        ).astype('category')
    if 'capital_loss' in df.columns:
        # capital_loss: bin_quantile bin into 1 groups → 'capital_loss_bin'
        df['capital_loss_bin'] = pd.cut(
            pd.to_numeric(df['capital_loss'], errors='coerce'), bins=[-1e-09, 3900.000000001],
            labels=['all'], include_lowest=True
        ).astype('category')

    # ============================================================
    # Stage: scaling
    # ============================================================
    if 'fnlwgt' in df.columns:
        # fnlwgt: robust-scale (median / IQR) → 'fnlwgt_scaled'
        _med = df['fnlwgt'].median()
        _iqr = df['fnlwgt'].quantile(0.75) - df['fnlwgt'].quantile(0.25)
        df['fnlwgt_scaled'] = (df['fnlwgt'] - _med) / max(float(_iqr), 1e-9)
    if 'capital_gain' in df.columns:
        # capital_gain: log1p transform → 'capital_gain_scaled'
        df['capital_gain_scaled'] = np.log1p(df['capital_gain'])
    if 'capital_loss' in df.columns:
        # capital_loss: log1p transform → 'capital_loss_scaled'
        df['capital_loss_scaled'] = np.log1p(df['capital_loss'])

    # ============================================================
    # Stage: encoding
    # ============================================================
    if 'native_country' in df.columns:
        # native_country: frequency encode → 'native_country_freq'
        _freq = df['native_country'].value_counts(normalize=True)
        df['native_country_freq'] = df['native_country'].map(_freq).fillna(0.0)

    return df


if __name__ == "__main__":
    _src           = sys.argv[1] if len(sys.argv) > 1 else _SOURCE_FILENAME
    _companion_dir = sys.argv[2] if len(sys.argv) > 2 else None
    cleaned = clean(_src, _companion_dir)

    cleaned.to_csv("clean.csv", index=False, lineterminator="\n")
    print(f"Wrote clean.csv  ({cleaned.shape[0]:,} rows × {cleaned.shape[1]} cols)")
