"""Output artifact (e) — the reproducible cleaning script.

Generates a standalone Python script (`clean_script.py`) that replays the
entire cleaning session on the raw input, with no dependency on the agent
or on an LLM. The script is plain `pandas` / `numpy` / `scikit-learn`
code — readable, editable, and deterministic.

The script is emitted from the decision log: every resolved DecisionCard
becomes one explicit, commented code block. Reading the script top to
bottom is reading exactly what the agent did and why.

Design:
  * Format-resolution decisions emit explicit pandas (rename, strip,
    sentinel-to-NaN, type coercion, label normalisation).
  * Missingness decisions emit drop / dropna / fillna; MICE (iterative
    regression) imputation emits a small self-contained scikit-learn block.
  * Outlier decisions emit fence-based clip / mask code from the recorded
    bounds.
  * Duplicate decisions emit drop_duplicates.
  * No-op decisions (leave_as_is, inspect, skipped) emit a comment only,
    so the audit trail stays complete.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import TYPE_CHECKING, Any

from .types import DecisionStatus, Stage

if TYPE_CHECKING:
    from .state import PipelineState, Session


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _tmpl_cols(tmpl: str) -> list[str]:
    """Return column names referenced by a match template."""
    import re
    refs = re.findall(r"\{(\w+)\}", tmpl)
    return refs if refs else [tmpl]


# ---------------------------------------------------------------------------
# Runtime dependency resolution (shared by the script docstring and the
# requirements.txt / environment.yml emitter)
# ---------------------------------------------------------------------------

# Minimum Python the generated script supports. Uses walrus (3.8+),
# `X | Y` type strings, f-strings; pinned to the project floor of 3.10.
_PY_REQUIRES = ">=3.10"
_PY_TESTED = "3.10–3.12"

# (package, pin, tested_version|None, why). tested_version is only set for
# packages whose end-to-end behaviour was actually verified at this version.
_PKG_PANDAS = ("pandas", ">=2.1", "2.3.3", "dataframe engine (always required)")
_PKG_NUMPY = ("numpy", ">=1.26", "2.2.6", "numeric arrays (always required)")
_PKG_SKLEARN = ("scikit-learn", ">=1.4", None, "MICE (iterative regression) imputation")
_PKG_PYARROW = ("pyarrow", ">=14.0", "24.0.0", "clean.parquet output")
_PKG_DATASETS = ("datasets", ">=2.18", "4.8.5", "HuggingFace Dataset (clean_dataset/)")
_PKG_PILLOW = ("Pillow", ">=10.0", "12.1.1", "decode companion images for HF Dataset")


def _runtime_packages(state: "PipelineState") -> list[tuple[str, str, str | None, str]]:
    """Return the exact package set the *generated script* needs to run.

    Conditional on what the script actually does: scikit-learn only when the
    session imputed, pyarrow only for parquet output, datasets+Pillow only for
    HF Dataset output. Pandas/numpy are always required.
    """
    cards = list(state.log)
    needs_mice = any(
        (c.action_taken or c.default_action) == "regression_impute"
        and c.stage == Stage.MISSINGNESS
        for c in cards
    )
    fmts = set(getattr(state, "output_formats", ["csv"]) or ["csv"])
    pkgs: list[tuple[str, str, str | None, str]] = [_PKG_PANDAS, _PKG_NUMPY]
    if needs_mice:
        pkgs.append(_PKG_SKLEARN)
    if "parquet" in fmts:
        pkgs.append(_PKG_PYARROW)
    if "hf" in fmts:
        pkgs.append(_PKG_DATASETS)
        if bool(state.companions):
            pkgs.append(_PKG_PILLOW)
    return pkgs


def emit_requirements(state: "PipelineState", session: "Session") -> dict[str, Path]:
    """Write `requirements.txt` and `environment.yml` next to the script.

    Documents the minimal, standalone dependency set for clean_script.py —
    pip pins plus a conda recipe — so a user with almost nothing installed can
    reproduce the run with a single command. Returns the written paths.
    """
    pkgs = _runtime_packages(state)
    name_w = max(len(f"{n}{pin}") for n, pin, _, _ in pkgs)

    req: list[str] = []
    r = req.append
    r("# ============================================================")
    r(f"# requirements.txt — runtime dependencies for clean_script.py")
    r(f"# Generated by Distill Agent (session {state.session_id}).")
    r("# ============================================================")
    r("# This script is STANDALONE — it needs only the packages below, not the")
    r("# full distill-agent project. Written for a fresh environment.")
    r("#")
    r(f"# Python {_PY_REQUIRES}   (tested on {_PY_TESTED})")
    r("#")
    r("# Quick start (pip + venv):")
    r("#     python -m venv .venv")
    r("#     source .venv/bin/activate        # Windows: .venv\\Scripts\\activate")
    r("#     pip install -r requirements.txt")
    r("#     python clean_script.py <your_input>")
    r("#")
    r("# Pins below are MINIMUMS; the 'tested' note records a known-good version.")
    r("# ------------------------------------------------------------")
    for n, pin, tested, why in pkgs:
        spec = f"{n}{pin}"
        note = f"tested {tested} — {why}" if tested else why
        r(f"{spec:<{name_w}}  # {note}")
    req_text = "\n".join(req) + "\n"

    env: list[str] = []
    e = env.append
    e("# Conda environment for clean_script.py — generated by Distill Agent.")
    e("# Create, activate, run:")
    e("#     conda env create -f environment.yml")
    e("#     conda activate distill-clean")
    e("#     python clean_script.py <your_input>")
    e("name: distill-clean")
    e("channels:")
    e("  - conda-forge")
    e("dependencies:")
    e(f"  - python{_PY_REQUIRES},<3.13")
    e("  - pip")
    e("  - pip:")
    for n, pin, _, _ in pkgs:
        e(f"      - {n}{pin}")
    env_text = "\n".join(env) + "\n"

    req_path = session.requirements_txt
    env_path = session.environment_yml
    req_path.write_text(req_text, encoding="utf-8")
    env_path.write_text(env_text, encoding="utf-8")
    return {"requirements": req_path, "environment": env_path}


# ---------------------------------------------------------------------------
# Public entry point
# ---------------------------------------------------------------------------


def emit_script(state: "PipelineState", session: "Session") -> Path:
    """Write `clean_script.py` to the session directory. Returns its path."""
    lines: list[str] = []
    a = lines.append

    cards = list(state.log)
    needs_mice = any(
        (c.action_taken or c.default_action) == "regression_impute"
        and c.stage == Stage.MISSINGNESS
        for c in cards
    )

    has_companions = bool(state.companions)
    tmpl = getattr(state, "companion_match_template", None)

    # Which output formats the analyst selected after cleaning. state.output_formats
    # is set in finalize(); default to CSV only. Drives both the docstring's OUTPUT
    # section and the generated __main__ block below.
    fmts = set(getattr(state, "output_formats", ["csv"]) or ["csv"])
    has_images = any(
        Path(c.path).suffix.lower() in {".png", ".jpg", ".jpeg", ".tiff", ".tif"}
        for c in state.companions
    )

    # Companion output shaping. The companion path / presence columns are
    # runtime plumbing (reconstructed by match_companions); by default they are
    # kept OUT of the cleaned tabular output. The companion_matching card records
    # whether the analyst opted to keep the path column (include_path action) or
    # a presence indicator (add_indicator action).
    _comp_card = next((c for c in cards if c.card_id == "companion_matching"), None)
    _comp_action = (
        (_comp_card.action_taken or _comp_card.default_action) if _comp_card else None
    )
    companion_drop_rows = _comp_action == "drop_rows"
    include_companion_path = bool(
        _comp_card and _comp_card.metadata.get("include_companion_path")
    )
    include_companion_indicator = bool(
        _comp_card and _comp_card.metadata.get("include_companion_indicator")
    )
    # companion_path / has_companion aliases are always dropped (user feedback:
    # uninformative). <type>_path kept only when include_path; has_<type> kept
    # only when add_indicator.
    _drop_from_table: set[str] = {"companion_path", "has_companion"}
    if not include_companion_path:
        _drop_from_table |= {"image_path", "audio_path", "text_path", "video_path"}
    if not include_companion_indicator:
        _drop_from_table |= {"has_image", "has_audio", "has_text", "has_video"}

    # ----- header -----
    src_name = state.input_path.name
    a('"""Reproducible cleaning script — generated by Distill Agent.')
    a("")
    a(f"Session : {state.session_id}")
    a(f"Source  : {src_name}")
    a(f"Result  : {state.n_rows_in:,}x{state.n_cols_in} raw  ->  "
      f"{len(state.df):,}x{len(state.df.columns)} clean")
    a("")
    a("This script replays the whole cleaning session deterministically.")
    a("It uses only pandas / numpy" + (" / scikit-learn" if needs_mice else "")
      + " — no LLM, no agent.")
    a("")
    # --- explicit input assumptions ---
    a("=" * 60)
    a("WHAT THIS SCRIPT EXPECTS AS INPUT")
    a("=" * 60)
    a("")
    a(f"The raw structured data file is:  {src_name}")
    a(f"  ({state.n_rows_in:,} rows x {state.n_cols_in} columns)")
    a("")
    if has_companions:
        n_comp = len(state.companions)
        mime_types = sorted({c.mime_type for c in state.companions})
        sample_names = [c.path.name for c in state.companions[:5]]
        a(f"Companion files: {n_comp} file(s)  [{', '.join(mime_types)}]")
        a(f"  Sample names : {', '.join(sample_names)}"
          + (f"  … +{n_comp - 5} more" if n_comp > 5 else ""))
        if tmpl:
            a(f"  Match rule   : filename stem = {tmpl!r}")
            a(f"                 (derived from columns: "
              + ", ".join(_tmpl_cols(tmpl)) + ")")
        a("")
        a("─" * 60)
        a("HOW TO CALL clean()")
        a("─" * 60)
        a("")
        a("Option 1 — ZIP containing both the CSV and the companion files:")
        a(f"    The ZIP must have {src_name!r} at its root (or any subfolder).")
        a("    Companion files must be in the same directory as the CSV inside")
        a("    the ZIP.  clean() will unpack and find them automatically.")
        a("")
        a("    python clean_script.py  your_archive.zip")
        a("    # or in Python:")
        a('    from clean_script import clean')
        a('    df = clean("your_archive.zip")')
        a("")
        a(f"Option 2 — {src_name!r} and companion files already unpacked:")
        a(f"    python clean_script.py  {src_name}  /path/to/companion/dir/")
        a("    # or in Python:")
        a('    from clean_script import clean')
        a(f'    df = clean("{src_name}", companion_dir="/path/to/companion/dir/")')
        a("")
        a("Option 3 — Structured output only (no companions):")
        a(f"    python clean_script.py  {src_name}")
        a("    # or in Python:")
        a('    from clean_script import clean')
        a(f'    df = clean("{src_name}")')
        a("    # No companion path columns are present in this case.")
    else:
        a("─" * 60)
        a("HOW TO CALL clean()")
        a("─" * 60)
        a("")
        a(f"    python clean_script.py  {src_name}")
        a("    # or in Python:")
        a('    from clean_script import clean')
        a(f'    df = clean("{src_name}")')
        a("    # You may also pass a pandas DataFrame directly:")
        a('    df = clean(your_raw_dataframe)')
    a("")
    a("OUTPUT")
    a("──────")
    a("Running this script produces the format(s) selected during cleaning:")
    if "csv" in fmts:
        a("clean.csv    — the cleaned, model-ready structured dataset")
        if has_companions and tmpl:
            if include_companion_path:
                a("             includes a companion path column (e.g. 'image_path')")
                a("             with the resolved local path for each row (None if missing)")
            elif include_companion_indicator:
                a("             includes a presence indicator column (e.g. 'has_image');")
                a("             companion file paths are reconstructed on demand by the script")
            else:
                a("             companion file paths are reconstructed on demand and are")
                a("             kept out of the saved table (run with a companion dir to use them)")
    if "parquet" in fmts:
        a("clean.parquet — same data in Parquet format (typed, compressed; needs pyarrow)")
    if "hf" in fmts:
        a("clean_dataset/ — HuggingFace Dataset (load via datasets.load_from_disk);")
        if has_companions and has_images:
            a("             companion images embedded as PIL, decoded lazily from the")
            a("             original files — no separate image folder needed at train time")
        else:
            a("             typed Arrow table, feeds HF Trainer / PyTorch DataLoader")
    a("")
    # --- environment / setup ---
    a("─" * 60)
    a("SETUP / ENVIRONMENT")
    a("─" * 60)
    a("")
    _pkgs = _runtime_packages(state)
    a(f"Requires Python {_PY_REQUIRES}  (tested on {_PY_TESTED}).")
    a("This script is standalone — it needs only these packages:")
    for _n, _pin, _, _why in _pkgs:
        a(f"    {_n}{_pin:<8}  # {_why}")
    a("")
    a("Install everything (a requirements.txt and environment.yml are written")
    a("alongside this script):")
    a("    pip install -r requirements.txt")
    a("    # or with conda:")
    a("    conda env create -f environment.yml && conda activate distill-clean")
    a("")
    a("=" * 60)
    a('"""')
    a("")
    a("from __future__ import annotations")
    a("")
    a("import sys")
    a("import tempfile")
    a("import zipfile")
    a("from pathlib import Path")
    a("")
    a("import numpy as np")
    a("import pandas as pd")
    a("")
    a(f'_SOURCE_FILENAME = {_pyrepr(state.input_path.name)}')
    a("")
    a("")

    # ----- optional MICE helper -----
    if needs_mice:
        a(_MICE_HELPER)
        a("")

    # ----- companion manifest (emitted before clean() so clean() can reference it) -----
    _emit_companion_constants(state, lines, session=session)

    # ----- _load_source() helper -----
    _emit_load_source(state, lines)

    # ----- clean() function -----
    a("def clean(")
    a("    source: 'str | Path | pd.DataFrame',")
    a("    companion_dir: 'str | Path | None' = None,")
    a(") -> pd.DataFrame:")
    a('    """Full pipeline: load → clean → join companions.')
    a("")
    a("    source may be:")
    a(f"      - a ZIP file containing the raw CSV and companion files")
    a(f"      - the raw CSV / Excel / Parquet path")
    a(f"      - a raw pandas DataFrame (companion_dir must be supplied separately)")
    a("")
    if has_companions and tmpl:
        a("    When companions are present and a companion_dir is supplied, the")
        a("    returned DataFrame carries the resolved companion path / presence")
        a("    columns (e.g. image_path, has_image). The saved tabular output keeps")
        a("    only the columns selected during cleaning; the HF Dataset embeds the")
        a("    companion files directly. Pass companion_dir to override where")
        a("    companion files are searched.")
    a('    """')
    a("    df, companion_dir = _load_source(source, companion_dir)")
    a("")

    target_col = getattr(state, "target_column", None)
    for stage in Stage:
        stage_cards = [c for c in cards if c.stage == stage]
        if not stage_cards:
            continue
        a(f"    # {'=' * 60}")
        a(f"    # Stage: {stage.value}")
        a(f"    # {'=' * 60}")
        for c in stage_cards:
            for code_line in _emit_card(c, target_col=target_col):
                a("    " + code_line if code_line else "")
        a("")

    # companion join — sets image_path / has_image / companion_path / has_companion
    # via runtime path existence checks; no sidecar manifest needed
    if has_companions and tmpl:
        a("    # join companion file paths — existence checked at runtime, no sidecar needed")
        a("    if companion_dir is not None:")
        a("        df = match_companions(df, companion_dir)")
        if companion_drop_rows:
            a("        # drop rows whose companion file was not found at runtime")
            a("        # (matching is by file existence — robust to new/changed data)")
            a("        _has_cols = [c for c in df.columns if c.startswith('has_')]")
            a("        if _has_cols:")
            a("            df = df[df[_has_cols].any(axis=1)].reset_index(drop=True)")
        a("")

    a("    return df")
    a("")
    a("")

    # ----- match_companions() helper (emitted whenever companions are present) -----
    _emit_match_companions(state, lines)

    # ----- to_hf_dataset() helper (module-level) -----
    # Emit it once whenever it could be needed: either companions with images
    # exist (so the analyst can call it by hand) or HF output was selected.
    # Emitting at module level — never inside __main__ — keeps the script valid.
    if (has_companions and has_images) or "hf" in fmts:
        _emit_to_hf_dataset(lines)

    a('if __name__ == "__main__":')
    a('    _src           = sys.argv[1] if len(sys.argv) > 1 else _SOURCE_FILENAME')
    a('    _companion_dir = sys.argv[2] if len(sys.argv) > 2 else None')
    a('    cleaned = clean(_src, _companion_dir)')
    a('')

    # Tabular outputs (CSV / Parquet) drop the companion plumbing columns by
    # default; the HF Dataset path keeps the full frame so images can embed.
    tabular_strips = bool(has_companions and tmpl and _drop_from_table)
    if tabular_strips and ("csv" in fmts or "parquet" in fmts):
        a(f"    _DROP_FROM_TABLE = {sorted(_drop_from_table)!r}")
        a("    # Companion path/presence columns are runtime plumbing — kept out")
        a("    # of the saved tabular data unless explicitly requested.")
        a("    _table = cleaned.drop(")
        a("        columns=[c for c in _DROP_FROM_TABLE if c in cleaned.columns]")
        a("    )")
        table_var = "_table"
    else:
        table_var = "cleaned"

    if "csv" in fmts:
        a(f'    {table_var}.to_csv("clean.csv", index=False, lineterminator="\\n")')
        a(f'    print(f"Wrote clean.csv  ({{{table_var}.shape[0]:,}} rows × {{{table_var}.shape[1]}} cols)")')

    if "parquet" in fmts:
        a("    try:")
        a(f'        {table_var}.to_parquet("clean.parquet", index=False)')
        a('        print("Wrote clean.parquet  (typed, compressed)")')
        a("    except ImportError as _e:")
        a('        print(f"Skipped clean.parquet — {_e}. Install with: pip install pyarrow")')

    if "hf" in fmts:
        # Build a HuggingFace Dataset directly from the cleaned table. When
        # companion paths resolved, they are embedded (images as PIL, etc.);
        # otherwise a table-only Arrow dataset is written. Self-contained:
        # `python clean_script.py data.zip` is enough to go zip -> HF object.
        a("    try:")
        a("        _hf_col = next(")
        a("            (c for c in ('image_path', 'audio_path', 'text_path')")
        a("             if c in cleaned.columns),")
        a("            None)")
        a("        _has_companions = bool(_hf_col) and bool(cleaned[_hf_col].notna().any())")
        a("        ds = to_hf_dataset(cleaned, image_col=_hf_col or 'image_path')")
        a('        ds.save_to_disk("clean_dataset/")')
        a("        if _has_companions:")
        a("            _n = int(cleaned[_hf_col].notna().sum())")
        a('            print(f"Wrote clean_dataset/  ({len(ds):,} rows, {_n:,} companions embedded)")')
        a("        else:")
        a('            print(f"Wrote clean_dataset/  ({len(ds):,} rows, table-only — '
          'no companion files resolved)")')
        a("    except ImportError as _e:")
        a('        print(f"Skipped clean_dataset/ — {_e}. '
          'Install with: pip install datasets Pillow")')

    a("")

    text = "\n".join(lines)
    out = session.clean_script
    out.write_text(text, encoding="utf-8")
    return out


# ---------------------------------------------------------------------------
# Per-card code emission
# ---------------------------------------------------------------------------


def _guard_col(lines: list[str], var: str) -> list[str]:
    """Wrap lines in an if-column-exists guard.

    All per-column transformations are guarded so the script runs safely on
    test/holdout sets that have a different schema (missing target, dropped
    columns, etc.) without crashing.
    """
    return [
        f"if {_pyrepr(var)} in df.columns:",
        *("    " + line for line in lines),
    ]


# Keep the old name as an alias so external callers aren't broken.
_guard_target = _guard_col


def _emit_card(card, target_col: str | None = None) -> list[str]:
    """Return the lines of code (un-indented) for one decision card.

    Every per-column transformation is wrapped in ``if '<col>' in df.columns:``
    so the script is safe to run on test/holdout sets that may have a different
    schema (e.g. missing target variable, or columns that were dropped during
    cleaning and are therefore absent from the holdout set).
    """
    cid = card.card_id
    action = card.action_taken or card.default_action
    var = card.variable

    def _g(lines: list[str]) -> list[str]:
        """Guard lines behind a column-existence check for any named variable."""
        if var:
            return _guard_col(lines, var)
        return lines

    # ----- Format stage -----
    if cid == "format_column_names":
        renames = card.metadata.get("renames", {})
        return [
            f"# rename {len(renames)} column(s) to snake_case",
            f"df = df.rename(columns={_pyrepr(renames)})",
        ]
    if cid.startswith("format_strip_ws__"):
        return _g([
            f"# {var}: strip leading/trailing whitespace",
            f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].where("
            f"df[{_pyrepr(var)}].isna(), df[{_pyrepr(var)}].astype(str).str.strip())",
        ])
    if cid.startswith("format_missing_tokens__"):
        toks = card.metadata.get("tokens_found", [])
        return _g([
            f"# {var}: convert missing-value sentinel(s) {toks} to NaN",
            f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].replace({_pyrepr(toks)}, np.nan)",
        ])
    if cid.startswith("format_coerce_numeric__"):
        return _g([
            f"# {var}: coerce to numeric",
            f"df[{_pyrepr(var)}] = pd.to_numeric(df[{_pyrepr(var)}], errors='coerce')",
        ])
    if cid.startswith("format_coerce_datetime__"):
        return _g([
            f"# {var}: parse to datetime",
            f"df[{_pyrepr(var)}] = pd.to_datetime(df[{_pyrepr(var)}], errors='coerce')",
        ])
    if cid.startswith("format_coerce_boolean__"):
        return _g([
            f"# {var}: coerce to boolean",
            f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].map("
            "{'true': True, 't': True, 'yes': True, 'y': True, '1': True, 1: True,"
            " 'false': False, 'f': False, 'no': False, 'n': False, '0': False, 0: False}"
            ").astype('boolean') if df[{0}].dtype == object "
            "else df[{0}].astype('boolean')".format(_pyrepr(var)),
        ])
    if cid.startswith("format_normalize_labels__"):
        mapping = card.metadata.get("label_mapping", {})
        return _g([
            f"# {var}: normalize {len(mapping)} categorical label variant(s)",
            f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].replace({_pyrepr(mapping)})",
        ])

    # ----- Missingness stage -----
    if card.stage == Stage.MISSINGNESS and var is not None:
        info = card.metadata.get("applied_info", {})
        if action == "drop_variable":
            return _g([f"# {var}: drop variable (too sparse)",
                    f"df = df.drop(columns=[{_pyrepr(var)}], errors='ignore')"])
        if action == "drop_rows":
            return _g([f"# {var}: drop rows with missing value",
                    f"df = df.dropna(subset=[{_pyrepr(var)}])"])
        if action in ("median_impute", "mean_impute", "mode_impute"):
            val = info.get("imputed_value")
            return _g([f"# {var}: {action} (imputed value recorded by the session)",
                    f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].fillna({_pyrepr(val)})"])
        if action == "regression_impute":
            if "fallback_from" in info:
                val = info.get("imputed_value")
                return _g([
                    f"# {var}: {action} requested; fell back to "
                    f"{info.get('applied')} (sklearn unavailable at run time)",
                    f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].fillna({_pyrepr(val)})",
                ])
            return _g([f"# {var}: MICE (iterative regression) over the numeric feature space",
                    f"df = _mice_impute(df, {_pyrepr(var)})"])
        if action == "flag_missing_indicator":
            return _g([f"# {var}: add missing-value indicator column",
                    f"df[{_pyrepr(str(var) + '_was_missing')}] = df[{_pyrepr(var)}].isna()"])
        if action == "leave_as_is":
            return [f"# {var}: missing values left in place (analyst decision)"]

    # ----- Outlier stage -----
    if card.stage == Stage.OUTLIER and var is not None:
        bounds = card.metadata.get("bounds", {})
        lo = bounds.get("iqr_low")
        hi = bounds.get("iqr_high")
        if action in ("leave_as_is", "inspect"):
            return [f"# {var}: outliers reviewed, no change ({action})"]
        if action == "winsorize" and lo is not None:
            return _g([f"# {var}: winsorize at the 1.5xIQR fence",
                    f"df[{_pyrepr(var)}] = df[{_pyrepr(var)}].clip("
                    f"lower={lo!r}, upper={hi!r})"])
        if action == "treat_as_missing" and lo is not None:
            return _g([
                f"# {var}: treat fence outliers (and negatives) as missing",
                f"_m = (df[{_pyrepr(var)}] < {lo!r}) | (df[{_pyrepr(var)}] > {hi!r}) "
                f"| (df[{_pyrepr(var)}] < 0)",
                f"df.loc[_m.fillna(False), {_pyrepr(var)}] = np.nan",
            ])
        if action == "drop_rows" and lo is not None:
            return _g([
                f"# {var}: drop rows with fence-outlier values",
                f"_m = (df[{_pyrepr(var)}] < {lo!r}) | (df[{_pyrepr(var)}] > {hi!r})",
                f"df = df[~_m.fillna(False)]",
            ])

    # ----- Duplicate stage -----
    if cid == "duplicates_exact":
        key_cols = card.metadata.get("key_columns", [])
        if action == "remove_all_duplicates":
            return ["# remove exact-duplicate rows, keep first of each group",
                    f"df = df.drop_duplicates(subset={_pyrepr(key_cols)}, keep='first')"]
        if action == "drop_all_duplicate_rows":
            return ["# drop every row that participates in an exact duplicate",
                    f"df = df[~df.duplicated(subset={_pyrepr(key_cols)}, keep=False)]"]
        return ["# exact duplicates: kept as-is (analyst decision)"]
    if cid.startswith("duplicates_near"):
        if action in ("merge_keep_first", "merge_keep_last"):
            idx = card.metadata.get("row_indices", [])
            keep = idx[:1] if action == "merge_keep_first" else idx[-1:]
            drop = [i for i in idx if i not in keep]
            return [f"# entity-key collision: {action}",
                    f"df = df.drop(index={_pyrepr(drop)}, errors='ignore')"]
        return [f"# near-duplicate cluster: {action} (no row change)"]

    # ----- Feature Engineering (Binning, Scaling, Encoding) -----
    if card.stage in (Stage.BINNING, Stage.SCALING, Stage.ENCODING):
        if action == "leave_as_is":
            return [f"# {var}: kept as-is (no {card.stage.value} applied)"]
        new_col = card.metadata.get("new_col") or card.metadata.get(
            "applied_info", {}
        ).get("new_col")
        if card.stage == Stage.BINNING and new_col:
            cut_points = (
                card.metadata.get("applied_info", {}).get("cut_points")
                or card.metadata.get("cut_points")
            )
            n_actual = len(cut_points) - 1 if cut_points else card.metadata.get("n_bins", 4)
            method = action  # e.g. "bin_quantile"
            if cut_points:
                from .binning import make_bin_labels
                labels = make_bin_labels([float(x) for x in cut_points])
                return _g([
                    f"# {var}: {method} bin into {n_actual} groups → '{new_col}'",
                    # Coerce to numeric first so binning is robust even if an
                    # earlier coercion step did not run on this column.
                    f"df[{_pyrepr(new_col)}] = pd.cut(",
                    f"    pd.to_numeric(df[{_pyrepr(var)}], errors='coerce'), bins={cut_points!r},",
                    f"    labels={labels!r}, include_lowest=True",
                    f").astype('category')",
                ])
            # fallback when cut_points were not recorded (should not happen)
            return _g([
                f"# {var}: bin ({method}) into {n_actual} groups → '{new_col}'",
                f"df[{_pyrepr(new_col)}] = pd.cut(pd.to_numeric(df[{_pyrepr(var)}], errors='coerce'), "
                f"bins={n_actual!r}, "
                f"labels=[f'bin_{{i+1}}' for i in range({n_actual!r})], include_lowest=True)",
            ])
        if card.stage == Stage.SCALING and new_col:
            method = action  # e.g. "scale_standard"
            if method == "scale_standard":
                return _g([
                    f"# {var}: standardise (z-score) → '{new_col}'",
                    f"_mu, _sd = df[{_pyrepr(var)}].mean(), df[{_pyrepr(var)}].std(ddof=1)",
                    f"df[{_pyrepr(new_col)}] = (df[{_pyrepr(var)}] - _mu) / max(float(_sd), 1e-9)",
                ])
            if method == "scale_minmax":
                return _g([
                    f"# {var}: min-max scale to [0, 1] → '{new_col}'",
                    f"_lo, _hi = df[{_pyrepr(var)}].min(), df[{_pyrepr(var)}].max()",
                    f"df[{_pyrepr(new_col)}] = (df[{_pyrepr(var)}] - _lo) / max(float(_hi - _lo), 1e-9)",
                ])
            if method == "scale_robust":
                return _g([
                    f"# {var}: robust-scale (median / IQR) → '{new_col}'",
                    f"_med = df[{_pyrepr(var)}].median()",
                    f"_iqr = df[{_pyrepr(var)}].quantile(0.75) - df[{_pyrepr(var)}].quantile(0.25)",
                    f"df[{_pyrepr(new_col)}] = (df[{_pyrepr(var)}] - _med) / max(float(_iqr), 1e-9)",
                ])
            if method == "scale_log":
                return _g([
                    f"# {var}: log1p transform → '{new_col}'",
                    f"df[{_pyrepr(new_col)}] = np.log1p(df[{_pyrepr(var)}])",
                ])
        if card.stage == Stage.ENCODING:
            if action == "frequency_encode" and new_col:
                return _g([
                    f"# {var}: frequency encode → '{new_col}'",
                    f"_freq = df[{_pyrepr(var)}].value_counts(normalize=True)",
                    f"df[{_pyrepr(new_col)}] = df[{_pyrepr(var)}].map(_freq).fillna(0.0)",
                ])
            if action == "datetime_decompose":
                components = card.metadata.get("components",
                    ["year", "month", "day", "dayofweek"])
                fe_lines = [f"# {var}: decompose datetime into components"]
                fe_lines.append(f"_dt = pd.to_datetime(df[{_pyrepr(var)}], errors='coerce')")
                for comp in components:
                    new_c = f"{var}_{comp}"
                    if comp == "is_weekend":
                        fe_lines.append(
                            f"df[{_pyrepr(new_c)}] = (_dt.dt.dayofweek >= 5).astype(int)"
                        )
                    else:
                        fe_lines.append(
                            f"df[{_pyrepr(new_c)}] = getattr(_dt.dt, {_pyrepr(comp)})"
                        )
                return _g(fe_lines)
        # FE fallback — note the transform for manual review
        return [f"# {var}: {card.stage.value} / {action} — reproduce manually if needed"]

    # ----- Companion matching (companion stage) -----
    # The actual data effects (row drop, path/indicator columns) are applied
    # right after match_companions() in clean(), using runtime path existence —
    # never a frozen subject-id list. Here we only emit a documenting comment so
    # the stage section records the decision.
    if cid == "companion_matching":
        n_unmatched = card.metadata.get("n_unmatched", 0)
        if action == "drop_rows":
            return [f"# companion matching: drop {n_unmatched} subject(s) with no "
                    "companion file (applied after match_companions, by file existence)"]
        if action == "add_indicator":
            return [f"# companion matching: {n_unmatched} subject(s) missing companion — "
                    "keep all rows, add has_<type> presence indicator"]
        if action == "flag_caveat":
            return [f"# companion matching: {n_unmatched} subject(s) missing companion — "
                    "noted in report, no rows dropped"]
        if action == "include_path":
            return ["# companion matching: complete coverage — companion path column kept"]
        if action == "exclude_path":
            return ["# companion matching: complete coverage — companion path column omitted"]
        return [f"# companion matching: {n_unmatched} subject(s) missing companion — "
                "kept (paths reconstructed on demand)"]

    # ----- fallback -----
    if card.status in (DecisionStatus.AGENT_AUTO, DecisionStatus.SKIPPED):
        return [f"# {card.stage.value}: {card.issue} (no data change)"]
    return [f"# {card.stage.value} / {cid}: action '{action}' — review manually"]


# ---------------------------------------------------------------------------
# Embedded MICE helper (only emitted when the session used regression imputation)
# ---------------------------------------------------------------------------

_MICE_HELPER = '''\
def _mice_impute(df: pd.DataFrame, var: str, random_state: int = 42) -> pd.DataFrame:
    """Self-contained MICE (iterative regression) imputation for one column.

    Numeric target: IterativeImputer (BayesianRidge, 10 rounds) fitted over
    all numeric columns. MICE is numeric-only, so a non-numeric target falls
    back to mode imputation — matching the session's categorical default.
    """
    out = df.copy()
    if not pd.api.types.is_numeric_dtype(out[var]):
        modes = out[var].mode(dropna=True)
        out[var] = out[var].fillna(modes.iloc[0] if len(modes) else None)
        return out
    from sklearn.experimental import enable_iterative_imputer  # noqa: F401
    from sklearn.impute import IterativeImputer

    num = [c for c in out.columns if pd.api.types.is_numeric_dtype(out[c])]
    imp = IterativeImputer(random_state=random_state, max_iter=10)
    out[num] = imp.fit_transform(out[num])
    return out
'''


def _emit_load_source(state: "PipelineState", lines: list[str]) -> None:
    """Emit _find_companion_dir() and _load_source() helpers."""
    has_companions = bool(state.companions)
    a = lines.append

    if has_companions:
        a("def _find_companion_dir(root: Path) -> 'Path | None':")
        a("    \"\"\"Return the directory under root that contains the most PNG files.\"\"\"")
        a("    from collections import Counter")
        a("    _pngs = list(root.rglob('*.png'))")
        a("    if not _pngs:")
        a("        return None")
        a("    return Counter(p.parent for p in _pngs).most_common(1)[0][0]")
        a("")
        a("")

    a("def _load_source(")
    a("    source: 'str | Path | pd.DataFrame',")
    a("    companion_dir: 'str | Path | None' = None,")
    a(") -> 'tuple[pd.DataFrame, Path | None]':")
    a('    """Read raw data from a file path, ZIP archive, or DataFrame."""')
    a("    if isinstance(source, pd.DataFrame):")
    a("        return source.copy(), Path(companion_dir) if companion_dir else None")
    a("    _p = Path(source)")
    a("    if _p.suffix.lower() == '.zip':")
    a("        _tmp = Path(tempfile.mkdtemp())")
    a("        with zipfile.ZipFile(_p) as _zf:")
    a("            _zf.extractall(_tmp)")
    a("        _candidates = list(_tmp.rglob(_SOURCE_FILENAME))")
    a("        if not _candidates:")
    a("            _candidates = sorted(_tmp.rglob('*.csv'))")
    a("        if not _candidates:")
    a("            raise FileNotFoundError(f'No CSV found inside {_p}.')")
    a("        # Prefer the CSV whose siblings include a target/label file (train split).")
    a("        def _priority(p: Path) -> int:")
    a("            siblings = {s.name.lower() for s in p.parent.iterdir()}")
    a("            return 0 if any(k in s for s in siblings")
    a("                           for k in ('train', 'dose', 'target', 'label')) else 1")
    a("        _main = sorted(_candidates, key=_priority)[0]")
    a("        if companion_dir is None:")
    if has_companions:
        a("            companion_dir = _find_companion_dir(_tmp) or _main.parent")
    else:
        a("            companion_dir = _main.parent")
    a("        return pd.read_csv(_main, dtype=object, keep_default_na=True), Path(companion_dir)")
    a("    _ext = _p.suffix.lower()")
    a("    if _ext in ('.xlsx', '.xls'):")
    a("        _df = pd.read_excel(_p, dtype=object)")
    a("    elif _ext == '.parquet':")
    a("        _df = pd.read_parquet(_p)")
    a("    elif _ext == '.json':")
    a("        _df = pd.read_json(_p, dtype=object)")
    a("    elif _ext in ('.sav',):")
    a("        _df = pd.read_spss(_p)")
    a("    elif _ext in ('.dta',):")
    a("        _df = pd.read_stata(_p)")
    a("    else:")
    a("        _df = pd.read_csv(_p, dtype=object, keep_default_na=True)")
    if has_companions:
        a("    if companion_dir is None:")
        a("        companion_dir = _find_companion_dir(_p.parent) or _p.parent")
    a("    return _df, Path(companion_dir) if companion_dir else None")
    a("")
    a("")


def _emit_to_hf_dataset(lines: list[str]) -> None:
    """Emit the to_hf_dataset() helper for image companions."""
    a = lines.append
    a("_PIPELINE_COLS = {")
    a("    'image_path', 'audio_path', 'text_path', 'video_path',")
    a("    'companion_path',")
    a("    'has_image', 'has_audio', 'has_text', 'has_video', 'has_companion',")
    a("}")
    a("")
    a("")
    a("def to_hf_dataset(")
    a("    df: pd.DataFrame,")
    a("    *,")
    a("    image_col: str = 'image_path',")
    a("    target_col: 'str | None' = None,")
    a(") -> 'datasets.Dataset':")
    a('    """Convert cleaned DataFrame to a HuggingFace Dataset with a native Image column.')
    a("")
    a("    Strips internal pipeline columns (image_path, has_image, companion_path,")
    a("    has_companion, etc.) so the HF Dataset contains only real features plus")
    a("    the 'image' column (PIL, decoded lazily from the original PNG bytes).")
    a("")
    a("    Requires: pip install datasets Pillow")
    a('    """')
    a("    import datasets")
    a("    from datasets import Image as HFImage")
    a("    out = df.copy()")
    a("    if image_col in out.columns:")
    a("        out = out.rename(columns={image_col: 'image'})")
    a("    out = out.drop(columns=[c for c in _PIPELINE_COLS if c in out.columns])")
    a("    if target_col and target_col in out.columns:")
    a("        out['label'] = pd.Categorical(out[target_col]).codes")
    a("        out = out.drop(columns=[target_col])")
    a("    for col in out.select_dtypes(include='object').columns:")
    a("        if col != 'image':")
    a("            try:")
    a("                out[col] = pd.to_numeric(out[col])")
    a("            except (ValueError, TypeError):")
    a("                pass")
    a("    ds = datasets.Dataset.from_pandas(out, preserve_index=False)")
    a("    if 'image' in ds.column_names:")
    a("        ds = ds.cast_column('image', HFImage())")
    a("    return ds")
    a("")
    a("")


def _emit_companion_constants(state: "PipelineState", lines: list[str], session: "Session | None" = None) -> None:
    """Emit the companion row-key helper (before clean()).

    Never emits a companion_manifest.json dependency. Companion filenames are
    fully determined by the key columns and a fixed extension — paths are
    derived and existence-checked at runtime inside match_companions().
    """
    if not state.companions:
        return
    tmpl = getattr(state, "companion_match_template", None)
    a = lines.append
    mime_types = sorted({c.mime_type for c in state.companions})

    a(f"# {'=' * 60}")
    a(f"# Companion files  ({len(state.companions)} file(s), {', '.join(mime_types)})")
    if tmpl:
        a(f"# Filename rule: {tmpl!r} + extension (e.g. .png)")
        a("# Paths are derived directly from key columns — no sidecar file needed.")
    else:
        a("#")
        a("# No match template was configured during cleaning.")
        a("# Pass match_col to match_companions() to specify the key column.")
    a(f"# {'=' * 60}")
    a("")

    if tmpl and "{" in tmpl and "}" in tmpl:
        import re as _re
        cols = _re.findall(r"\{(\w+)\}", tmpl)
        parts = []
        segments = _re.split(r"\{\w+\}", tmpl)
        for i, seg in enumerate(segments):
            if seg:
                parts.append(_pyrepr(seg))
            if i < len(cols):
                parts.append(f'df[{_pyrepr(cols[i])}].fillna("").astype(str)')
        a("def _companion_row_keys(df: pd.DataFrame) -> pd.Series:")
        a(f'    """Derive the companion match key for each row using template {tmpl!r}."""')
        a(f"    return {' + '.join(parts)}")
        a("")
    a("")


def _emit_match_companions(state: "PipelineState", lines: list[str]) -> None:
    """Emit the match_companions() helper function.

    Uses direct path construction + Path.exists() — never a glob scan or
    sidecar manifest. has_companion / has_image are set from actual file
    existence at runtime.
    """
    if not state.companions:
        return
    tmpl = getattr(state, "companion_match_template", None)
    is_compound = tmpl and "{" in tmpl and "}" in tmpl
    a = lines.append

    # Infer the dominant extension from the companions recorded in the session.
    from collections import Counter
    ext_counts: Counter = Counter(
        Path(c.path).suffix.lower() for c in state.companions
    )
    dominant_ext = ext_counts.most_common(1)[0][0] if ext_counts else ".png"

    a("def match_companions(")
    a("    df: pd.DataFrame,")
    a("    companion_dir: 'str | Path',")
    a("    *,")
    a(f"    extensions: 'list[str] | None' = None,")
    a(") -> pd.DataFrame:")
    a('    """Add companion path columns by checking existence of derived filenames.')
    a("")
    a("    For each row constructs the expected filename as")
    if tmpl:
        a(f"    {tmpl!r} + extension (default {dominant_ext!r}),")
    else:
        a("    <match_col_value> + extension,")
    a("    checks whether that file exists in companion_dir, and adds:")
    a("      <type>_path  — absolute path string, or None when file not found")
    a("      has_<type>   — True / False")
    a("")
    a("    No sidecar file required — paths derived entirely from data columns.")
    a('    """')
    a("    _IMAGE = {'.png', '.jpg', '.jpeg', '.tiff', '.tif'}")
    a("    _AUDIO = {'.wav', '.mp3', '.flac'}")
    a("")
    a("    def _prefix(ext: str) -> str:")
    a("        e = ext.lower()")
    a("        if e in _IMAGE: return 'image'")
    a("        if e in _AUDIO: return 'audio'")
    a("        if e == '.txt': return 'text'")
    a("        return e.lstrip('.')")
    a("")
    a(f"    if extensions is None:")
    a(f"        extensions = [{dominant_ext!r}]")
    a("    companion_dir = Path(companion_dir)")
    if is_compound:
        a("    keys = _companion_row_keys(df)")
    else:
        key_col = tmpl if tmpl else "match_col"
        a(f"    keys = df[{_pyrepr(key_col)}].fillna('').astype(str)")
    a("    out = df.copy()")
    a("    for ext in extensions:")
    a("        prefix = _prefix(ext)")
    a("        paths = [")
    a("            str(p) if (p := companion_dir / f\"{k}{ext}\").exists() else None")
    a("            for k in keys")
    a("        ]")
    a("        out[f\"{prefix}_path\"] = paths")
    a("        out[f\"has_{prefix}\"] = [p is not None for p in paths]")
    a("    return out")
    a("")
    a("")


def _pyrepr(value: Any) -> str:
    """A safe Python literal for the value (uses json for nested structures)."""
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=True)
    return repr(value)
